import os
import shutil
import zipfile
import json
import requests
import time
from rich.console import Console
from rich.prompt import Prompt
from rich.progress import Progress
from rich.panel import Panel

console = Console()
PROJECTS_DIR = os.path.expanduser("~/mf2_projects")

# --- СЕТЬ ---

def get_fabric_versions():
    console.print("[cyan]🔍 Поиск версий Minecraft...[/]")
    try:
        url = "https://meta.fabricmc.net/v2/versions/game"
        response = requests.get(url, timeout=5)
        data = response.json()
        return [v['version'] for v in data if v['stable']]
    except:
        console.print("[red]⚠️ Ошибка сети. Использую оффлайн-список.[/]")
        return ["1.21.11", "1.21.4", "1.21.1", "1.20.1"]

def get_yarn_version(mc_version):
    console.print(f"[cyan]🔍 Поиск Yarn для {mc_version}...[/]")
    try:
        url = f"https://meta.fabricmc.net/v2/versions/yarn/{mc_version}"
        response = requests.get(url, timeout=5)
        data = response.json()
        if data:
            latest = data[0]['version']
            console.print(f"[green]✅ Найдeн: {latest}[/]")
            return latest
    except: pass
    console.print(f"[yellow]⚠️ Yarn не найден (будет использован Official)[/]")
    return None

def download_template(target_folder):
    url = "https://github.com/FabricMC/fabric-example-mod/archive/refs/heads/master.zip"
    try:
        with Progress() as progress:
            task = progress.add_task("[green]Скачивание шаблона...", total=None)
            r = requests.get(url, stream=True)
            zip_path = os.path.join(target_folder, "temp.zip")
            os.makedirs(target_folder, exist_ok=True)
            with open(zip_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)
            progress.update(task, completed=100, description="[green]Распаковка...")
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(target_folder)
            os.remove(zip_path)
            extracted = os.path.join(target_folder, "fabric-example-mod-master")
            if os.path.exists(extracted):
                for item in os.listdir(extracted):
                    shutil.move(os.path.join(extracted, item), target_folder)
                os.rmdir(extracted)
            return True
    except Exception as e:
        console.print(f"[red]❌ Ошибка: {e}[/]")
        return False

# --- НАСТРОЙКИ ---

def update_gradle_wrapper(project_path):
    # Gradle 8.14 (Требование Loom 1.11+)
    wrapper = os.path.join(project_path, "gradle", "wrapper", "gradle-wrapper.properties")
    if not os.path.exists(wrapper): return
    content = (
        "distributionBase=GRADLE_USER_HOME\n"
        "distributionPath=wrapper/dists\n"
        "distributionUrl=https\://services.gradle.org/distributions/gradle-8.14-bin.zip\n"
        "zipStoreBase=GRADLE_USER_HOME\n"
        "zipStorePath=wrapper/dists\n"
    )
    with open(wrapper, 'w') as f: f.write(content)
    console.print("[green]✅ Gradle Wrapper -> 8.14[/]")

def update_loom_version(project_path):
    # Loom 1.9-SNAPSHOT (Для Gradle 8.x)
    build = os.path.join(project_path, "build.gradle")
    if not os.path.exists(build): return
    lines = []
    with open(build, 'r') as f:
        for line in f:
            if "id 'fabric-loom' version" in line or 'id "fabric-loom" version' in line:
                lines.append("    id 'fabric-loom' version '1.9-SNAPSHOT'\n")
            else:
                lines.append(line)
    with open(build, 'w') as f: f.writelines(lines)
    console.print("[green]✅ Fabric Loom -> 1.9-SNAPSHOT[/]")

def configure_gradle_properties(project_path, mc_ver, yarn_ver, map_type, mod_ver, group, loader_ver):
    props = os.path.join(project_path, "gradle.properties")
    
    # Loader берем из аргумента (0.18.4)
    content = f"""
# Auto-generated by MF2
minecraft_version={mc_ver}
loader_version={loader_ver}
mod_version={mod_ver}
maven_group={group}
archives_base_name={group.split('.')[-1]}
fabric_version=0.100.8+1.21

# Optimization
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false
org.gradle.configuration-cache=true
"""
    if map_type == "yarn" and yarn_ver:
        content += f"yarn_mappings={yarn_ver}\n"
    else:
        content += "mappings_channel=official\n"

    with open(props, 'w') as f: f.write(content)
    console.print(f"[green]✅ Config настроен: Loader {loader_ver} | {map_type}[/]")

def edit_fabric_json(project_path, mod_id, mod_name, mod_ver):
    json_path = os.path.join(project_path, "src", "main", "resources", "fabric.mod.json")
    if not os.path.exists(json_path): return
    try:
        with open(json_path, 'r') as f: data = json.load(f)
        data['id'] = mod_id
        data['name'] = mod_name
        data['version'] = mod_ver
        data['authors'] = ["MF2 User"]
        data['contact']['homepage'] = "https://example.com"
        with open(json_path, 'w') as f: json.dump(data, f, indent=4)
    except: pass

def refactor_java_package(project_path, new_package):
    base_src = os.path.join(project_path, "src", "main", "java")
    old_pkg = None
    
    for r, _, f in os.walk(base_src):
        for file in f:
            if file.endswith(".java"):
                with open(os.path.join(r, file), 'r') as fh:
                    for line in fh:
                        if line.startswith("package "):
                            old_pkg = line.split(" ")[1].rstrip(";\n")
                            break
            if old_pkg: break
        if old_pkg: break
    
    if not old_pkg or old_pkg == new_package: return

    new_dir = os.path.join(base_src, *new_package.split("."))
    os.makedirs(new_dir, exist_ok=True)
    old_dir = os.path.join(base_src, *old_pkg.split("."))
    
    if os.path.exists(old_dir):
        for item in os.listdir(old_dir):
            s = os.path.join(old_dir, item)
            d = os.path.join(new_dir, item)
            if os.path.isfile(s):
                shutil.move(s, d)
                if s.endswith(".java"):
                    with open(d, 'r') as f: txt = f.read()
                    with open(d, 'w') as f: f.write(txt.replace(f"package {old_pkg}", f"package {new_package}"))
    try: shutil.rmtree(os.path.join(base_src, old_pkg.split(".")[0]))
    except: pass
    console.print(f"[green]✅ Пакеты обновлены: {new_package}[/]")

# --- ЗАПУСК ---

def run():
    console.clear()
    console.print(Panel("[bold green]MASTER WIZARD: New Project[/]", border_style="green"))

    # 1. MC Version
    versions = get_fabric_versions()
    mc_version = Prompt.ask("MC Version", choices=versions, default=versions[0])

    # 2. Loader Version (АВТОМАТИЧЕСКИ ПРЕДЛАГАЕМ 0.18.4)
    default_loader = "0.18.4" if "1.21" in mc_version else "0.16.10"
    loader_version = Prompt.ask("Fabric Loader Version", default=default_loader)

    # 3. Mappings
    map_type = Prompt.ask("Mappings Type", choices=["yarn", "official"], default="yarn")
    yarn_ver = None
    if map_type == "yarn":
        yarn_ver = get_yarn_version(mc_version)
        if not yarn_ver:
            console.print("[yellow]⚠️ Yarn не найден, использую Official[/]")
            map_type = "official"

    # 4. Info
    package_base = Prompt.ask("Package Group", default="com.nl")
    mod_name = Prompt.ask("Mod Name")
    mod_version = Prompt.ask("Mod Version (1.0.0 -> Rel.Beta.Demo)", default="1.0.0")

    mod_id = mod_name.lower().replace(" ", "_")
    full_package = f"{package_base}.{mod_id}"
    
    project_folder = os.path.join(PROJECTS_DIR, mod_id)
    if os.path.exists(project_folder):
        console.print("[red]❌ Папка занята![/]")
        time.sleep(1)
        return

    console.print("\n[yellow]⚡ Генерация...[/]")
    
    if download_template(project_folder):
        # Передаем правильный loader_version (0.18.4)
        configure_gradle_properties(project_folder, mc_version, yarn_ver, map_type, mod_version, package_base, loader_version)
        update_gradle_wrapper(project_folder)
        update_loom_version(project_folder)
        edit_fabric_json(project_folder, mod_id, mod_name, mod_version)
        refactor_java_package(project_folder, full_package)
        
        console.print(f"\n[bold green]🎉 Проект {mod_id} создан![/]")
        
        if Prompt.ask("Открыть сейчас?", choices=["y", "n"], default="y") == "y":
            import MainProject
            MainProject.run(mod_id)